### ISSUE TITLE
LinkedIn validation needs fixing

### ISSUE THREAD

**Issue by amishshah** [unicsmcr/unics_social_api#101]
The current LinkedIn validation needs to be changed to be uniform with the other social media, i.e. accept the handle itself and not the rest of the URL. This is partly for security reasons (e.g. current regex would accept HTTP URLs) and also because the rest of the URL is basically irrelevant, we can construct the full URL from just the user's handle.

We could implement some functionality on the frontend to accept a full URL for each social media, and parse it for just the handle before interacting with the API. But for now, the validation needs to be updated to only accept the handle on the backend (the XYZ In `https://linkedin.com/in/XYZ`).

**Comment by akyrey** [comment]
Hello, I'd like to contribute on this one, if possible. It's my first contribution, let me know if I do something wrong or miss something.

Thank you

**Comment by amishshah** [comment]
Resolved in https://github.com/unicsmcr/unics_social_api/pull/102, thanks @akyrey!
