### ISSUE TITLE
Remove UniCS-specific branding

### ISSUE THREAD

**Issue by amishshah** [unicsmcr/unics_social_api#128]
## About

To make KB accessible to those not doing a CS-related degree, they should be able to select their own degree. We need to collect the full list of courses available at UoM, and then also the department/school information for each course. This can be achieved by the solution discussed here https://github.com/unicsmcr/unics_social_api/issues/128#issuecomment-712962022.

After the scraping is done, the enum of courses needs to be updated.

## Original discussion:

The back-end currently places restrictions on the courses that users can take (e.g. all CS-related courses exist as actual values, any other course is just "Other").

As we are now pushing this for other societies to use (that aren't related to CS), we need to re-think the courses section on a user's profile.

- Should we allow users to enter any text for their course?
- What if people only want to match with people from their course/related course - how would this be achieved? Maybe we could ask students to pick their department/school additionally, and allow them to match with people from the same school/department? That allows them to meet people on the same/related course to them.

**Comment by RegsonDR** [comment]
How often do courses get added/removed by UoM? I think it would probably be better if all courses were pre-defined, allowing it as completely free text could cause variation and duplicates, for example, bsc computer science, computer science, bsc cs, computer sience (typo intended).. it would be a bit chaotic to match users like that.  Alternatively, when typing in their course, it could be auto-suggested to them as they type it in or something like a 'Did you mean ... ' ? 

A school/department option is a lot easier and sounds good! Food for thought, here's some more possible matching ideas for the future: interests (sports/activities/games), background (country), gender, age group, town .. etc

**Comment by amishshah** [comment]
A predefined course list could work and could be scraped from [https://www.manchester.ac.uk/study/undergraduate/courses/2021/](https://www.manchester.ac.uk/study/undergraduate/courses/2021/). If we went with that, the auto-fill option sounds good.

However, I don't think that list contains any "departmental" info for each course which is a bit annoying. I agree and think the best way to move forward is being able to select a faculty/department instead of a specific course, see [https://www.manchester.ac.uk/discover/structure/faculties-schools/](https://www.manchester.ac.uk/discover/structure/faculties-schools/).

This would require some breaking changes, but I think it is the best way forward for pairing up users outside of CS for now. Proposed options:

- School of Biological Sciences
- School of Medical Sciences
- School of Health Sciences
- School of Engineering
- School of Natural Sciences
- School of Arts, Languages and Cultures
- School of Environment, Education and Development
- School of Social Sciences

The last 2 could be expanded to show the departments in the school (see the above link), but I felt that could become very specific. What does everyone think?

-----

> Food for thought, here's some more possible matching ideas for the future: interests (sports/activities/games), background (country), gender, age group, town .. etc

That sounds great @RegsonDR! Could you create an issue for that and then we can look at implementing it in the future at some point.

**Comment by RegsonDR** [comment]
> A predefined course list could work and could be scraped from https://www.manchester.ac.uk/study/undergraduate/courses/2021/. If we went with that, the auto-fill option sounds good. However, I don't think that list contains any "departmental" info for each course which is a bit annoying. 

Whilst it's not possible to obtain the school/faculty directly from this listing page, the information does seem to be available on each course individually. So we would need 2 levels of scraping (list then course), we can get the course URL from the initial scrape for hrefs.  I think it should be pretty easy to scrape the department because it seems to be stored in a "department" class. Some courses seem to have schools here but we can map these departments/schools across to a faculty using the info from your 2nd link as that's a more manageable amount.

![image](https://user-images.githubusercontent.com/32569720/96612213-66728200-12f5-11eb-8dbf-f32311bc4e78.png)

So we can allow people to choose their course and that would fetch their departments too, that would be helpful as some people may not even know their departments.

> That sounds great @RegsonDR! Could you create an issue for that and then we can look at implementing it in the future at some point.

Will do. 👍

**Comment by amishshah** [comment]
I'm happy with that solution @RegsonDR. We will continue to store courses in the database, and we can derive the department from the course separately.

**Comment by RegsonDR** [comment]
https://www.manchester.ac.uk/study/masters/courses/list/

^ Link to the Masters course list, similar page layout for the course list, and the same page layout for the individual course detail.
